baseURL = 'https://okoyo.dev/'
languageCode = 'en-us'
title = "Okoyo's Portofolio"
enableRobotsTXT = true
defaultContentLanguage = "en"

[params]
  author = "Okoyo"
  description = "This is My Portofolio"
  showDarkModeToggler = true
  disableScrollAnimation = true
  showMenuItems = true
  copyright = "© 2024 Okoyo"

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[privacy]
  [privacy.youtube]
    disableJS = true
  [privacy.googleAnalytics]
    anonymizeIP = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = []
  term = []
